### ISSUE TITLE
September 24, morning session code review.

### ISSUE THREAD

**Issue by Meltrust** [Wikitelmex/ToDoProject#4]
Hi Alex!

A great project so far!! 🥇 

However, I noticed some things that could be improved!!

1.  On crudtask.js line 22, Eslint won't like the `index++`.   It wants you to write it like this: `n += 1`.   That way you won't have to disable the rule.
2. Your files seem a little messy.  You could add a folder named "modules" and put all the exporting files there.  
3. Please don't forget to eliminate all the commented code before the review request.
4. If you encapsulate your modules into classes with methods instead of loose functions, your code will be tighter and a lot more readable.

Happy coding! 💯

**Comment by Wikitelmex** [comment]
tyvm for review, it was worked to make that improvements.
